### ISSUE TITLE
Tomcat v6 end of life  2016-12-31

### ISSUE THREAD

**Issue by ilessing** [geerlingguy/ansible-role-tomcat6#2]
Tomcat v6 is _end of life_ soon.
When I try to run this role it fails as the YUM package isn't found.

```
[vagrant@localhost ~]$ sudo yum install tomcat6
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.supremebytes.com
 * epel: mirror.cs.ucsb.edu
 * extras: mirror.supremebytes.com
 * updates: mirror.keystealth.org
No package tomcat6 available.
Error: Nothing to do
```

ref: http://tomcat.apache.org/tomcat-60-eol.html

**Comment by geerlingguy** [comment]
Yeah, I don't actually use this role anymore either... so we should probably put a big DEPRECATED notice on it somewhere.

**Comment by ilessing** [comment]
What role do you use now?

BTW... working from your Ansible for DevOps book.  Thank You!

**Comment by geerlingguy** [comment]
@ilessing - In the latest book revisions (posted first to LeanPub, then quarterly to iBooks and Amazon, as well as to published hardcopy revisions), I am using Solr's built-in Jetty server with Java directly—see updated example code here: https://github.com/geerlingguy/ansible-for-devops/tree/master/solr

**Comment by geerlingguy** [comment]
(Therefore I don't have any personal projects where I need to use Tomcat :)
